import assert from 'node:assert/strict';
export function coldContracts({test,env,plain,answers}) {
 const pc={approach:'cold',suitability:'Public B2B companies can be identified; need unknown',limitations:['No expressed need'],cold_min_fit:65,
  cold_priority:{fit_weight:.7,contact_weight:.2,timing_weight:.1,half_life_days:30},contacts:{provider:'hunter',monthly_credits:5,max_rows_per_run:5,cache_days:30,verification_days:30}};
 const setup=(patch={})=>env([],{mode:'assisted',decision_roles:['owner','operations director'],prospecting:structuredClone(pc),...patch});
 const contact={lead_id:'cold:a',contact_id:'c1',company:'Example Co',domain:'example.com',name:'Alice Example',role:'Operations director',
  identity_status:'confirmed',email:'alice@example.com',verified_email:'alice@example.com',email_status:'valid',verified_on:new Date(),do_not_contact:''};
 const input={searchStringsArray:['clinics'],locationQuery:'Example city',maxCrawledPlacesPerSearch:10,language:'en',scrapePlaceDetailPage:false,scrapeContacts:false,maximumLeadsEnrichmentRecords:0,verifyLeadsEnrichmentEmails:false,maxReviews:0,maxImages:0,enableCompetitorAnalysis:false};
 const headers=['lead_id','contact_id','company','domain','name','role','linkedin','identity_status','email','email_status','verified_on','source_urls','checked_on','note','do_not_contact','verified_email','published_email','provider','provider_person_id','phone','phone_type','phone_status','phone_checked_on','pending_request_id'];
 function attachContacts(e,records){
  const writes=[],sheet={getName:()=> 'Contacts',getActiveRangeList:()=>null,getActiveRange:()=>({getRow:()=>2,getLastRow:()=>2}),isRowHiddenByFilter:()=>false,appendRow:row=>records.push(Object.fromEntries(headers.map((k,i)=>[k,row[i]??'']))),getDataRange:()=>({getValues:()=>[headers,...records.map(c=>headers.map(k=>c[k]??''))]}),
   getRange:(row,col)=>({setValue:v=>{writes.push({row,col,v});records[row-2][headers[col-1]]=v;}})};
  e.sheets.Contacts=sheet;const original=e.s.SpreadsheetApp.getActive;e.s.SpreadsheetApp.getActive=()=>({...original(),getActiveSheet:()=>sheet});return {sheet,writes,records};
 }
 function discoveryFixture(leads,records=[]){
  const e=env(leads,{mode:'assisted',decision_roles:['owner','operations director'],prospecting:structuredClone(pc)}),f=attachContacts(e,records),ss=e.s.SpreadsheetApp.getActive();
  let selectedRow=3;
  Object.assign(e.sheets.Leads,{getActiveRangeList:()=>null,getActiveRange:()=>({getRow:()=>selectedRow,getLastRow:()=>selectedRow,getColumn:()=>1,getLastColumn:()=>1}),isRowHiddenByFilter:()=>false});
  e.s.SpreadsheetApp.getActive=()=>({...ss,getActiveSheet:()=>e.sheets.Leads,setActiveSheet:()=>{}});
  e.s.SpreadsheetApp.getUi=()=>({alert:()=>1,ButtonSet:{OK_CANCEL:1},Button:{OK:1}});
  e.s.contactSheets_=()=>({contacts:f.sheet});
  return {...e,...f,select:row=>{selectedRow=row;}};
 }
 const coldLead={id:contact.lead_id,source:'cold_prospect',company:'Example',website:'https://example.com',status:'new',match_pct:85,contact:''};
 const domainResult={domain:'example.com',emails:[{value:contact.email,type:'personal',first_name:'Alice',last_name:'Example',position:'Operations director'}]};
 test('cold company can fit while intent and readiness remain unknown',()=>{const e=setup(),a=answers(e,.9);a.poster={choice:'seller',confidence:.99};a.pitch={choice:'none'};const r=e.s.jevDerive_(a,{source:'cold_prospect',company:'Example'});assert.equal(r.match_pct,90);assert.equal(r.readiness_pct,'Unknown');assert.equal(r.next_step,'You decide');assert.equal(r.ai_pitch,'exploratory');assert.match(e.s.jevState_({source:'cold_prospect'}).opportunity_type,/UNKNOWN/);});
 test('cold rejected site still withholds fit',()=>{const e=setup(),a=answers(e);a.site_matches_post={noul:.1};assert.equal(e.s.jevDerive_(a,{source:'cold_prospect',_site:{text:'wrong'}}).match_pct,'');});
 test('cold unknown readiness is not repeatedly queued as missing',()=>{const e=setup();assert.equal(e.s.missingLeadScores_({source:'cold_prospect',match_pct:85,readiness_pct:'Unknown',next_step:'You decide'}),false);assert.deepEqual(plain(e.s.cellFillPlan_({source:'cold_prospect',match_pct:80,readiness_pct:'Unknown'},['priority_pct']).fields),['priority_pct']);});
 test('cold priority uses verified contacts and supported timing, never collection date',()=>{const f=setup().s.coldPriorityFormula_(c=>'['+c+']');assert.match(f,/confirmed/);assert.match(f,/valid/);assert.match(f,/Prospect evidence/);assert.doesNotMatch(f,/\[added\]|\[posted\]|\[readiness_pct\]/);});
 test('cold company CSV deduplicates domain and separates facts from hypothesis',()=>{const e=setup(),h=['company','website','facts','facts_url','hypothesis'];const a=e.s.coldProspectsCsv_([h,['Example','https://example.com','Has two offices','https://example.com/about','May need workflow help']])[0];const b=e.s.coldProspectsCsv_([h,['Renamed Example','https://www.example.com/','Has three offices','https://example.com/about','Could need support']])[0];assert.equal(a.lead.id,b.lead.id);assert.equal(a.lead.readiness_pct,'Unknown');assert.equal(a.lead.posted,undefined);assert.match(a.lead.notes,/Hypothesis \(unconfirmed\)/);assert.equal(a.evidence[3],'May need workflow help');});
 test('cold CSV refuses future or unsupported timing',()=>{const e=setup(),h=['company','website','facts','facts_url','hypothesis','timing_signal','timing_date','timing_url'];assert.throws(()=>e.s.coldProspectsCsv_([h,['A','example.com','office','https://example.com','need?','new office','2999-01-01','https://example.com/news']]),/Timing/);});
 test('company import does not accept LinkedIn as its own business domain',()=>{const s=setup().s;assert.equal(s.professionalDomain_('https://linkedin.com/company/example'),'');assert.equal(s.professionalDomain_('https://user:pass@example.com'),'');assert.equal(s.professionalDomain_('https://example.com'),'example.com');});
 test('Maps adapter preserves branch IDs and refuses manufactured need/date',()=>{const e=setup(),rows=e.s.normalise_('company_directory',[{title:'Branch A',placeId:'p1',categoryName:'Clinic',website:'https://example.com',url:'https://maps.google.com/?cid=123',scrapedAt:'2026-09-28'},{title:'Branch B',placeId:'p2',categoryName:'Clinic',website:'https://example.com',url:'https://maps.google.com/?cid=456'}]);assert.equal(rows.length,2);assert.notEqual(rows[0].id,rows[1].id);assert.equal(rows[0].source,'cold_prospect');assert.equal(rows[0].posted,'');assert.equal(rows[0].contact,'');assert.match(rows[0].what_they_want,/unconfirmed/);});
 test('Maps closed and malformed records do not become active prospects',()=>{const e=setup();assert.equal(e.s.normalise_('company_directory',[{title:'Closed',permanentlyClosed:true}]).length,0);assert.equal(e.s.normalise_('company_directory',[{title:'No ID'}]).length,0);assert.ok(e.events.some(x=>x.type==='error'));});
 test('editable directory input cannot quietly enable expensive extras',()=>{const e=setup();assert.equal(e.s.directoryInputValid_(input),true);for(const bad of [{scrapeContacts:true},{maximumLeadsEnrichmentRecords:1},{maxCrawledPlacesPerSearch:100},{searchStringsArray:['a','b']},{website:'allPlaces'}])assert.equal(e.s.directoryInputValid_({...input,...bad}),false);assert.throws(()=>e.s.validateSourceRow_(['company_directory',true,'compass/crawler-google-places',.05,JSON.stringify({...input,scrapeContacts:true}),'']),/bounded/);});
 test('Hunter domain candidates require role and company-domain agreement',()=>{const e=setup(),p={value:'alice@example.com',type:'personal',first_name:'Alice',last_name:'Example',position:'Operations director',linkedin:'https://linkedin.com/in/alice?trk=x',verification:{status:'valid',date:'2026-09-20'}};const r=e.s.hunterCandidates_({domain:'example.com',emails:[p]},{id:'a',company:'A',website:'https://example.com'});assert.equal(r.length,1);assert.equal(r[0].identity_status,'unconfirmed');assert.equal(r[0].linkedin,'https://www.linkedin.com/in/alice');assert.equal(e.s.hunterCandidates_({domain:'elsewhere.com',emails:[p]},{website:'https://example.com'}).length,0);});
 test('assistant to owner is not accepted as the owner',()=>{assert.equal(setup().s.contactRoleMatches_('Assistant to owner'),false);});
 test('role match accepts director of operations word order',()=>{assert.equal(setup().s.contactRoleMatches_('Director of Operations'),true);});
 test('LinkedIn mentions and company pages never become person profiles',()=>{const s=setup().s;for(const u of ['https://linkedin.com/posts/other','https://linkedin.com/company/example','https://linkedin.com.evil.example/in/alice'])assert.equal(s.canonicalLinkedIn_(u),'');});
 test('consumer and unrelated mailbox cannot publish as work email',()=>{const s=setup().s;assert.equal(s.workEmail_('alice@gmail.com','example.com'),'');assert.equal(s.workEmail_('alice@other.com','example.com'),'');assert.equal(s.workEmail_('noreply@example.com','example.com'),'');});
 test('provider fixed dummy identity is rejected for different requested person',()=>{const s=setup().s,r=s.finderResult_({first_name:'Richard',last_name:'Hendricks',domain:'piedpiper.com',email:'richard@piedpiper.com',verification:{status:'valid'}},{...contact,email:''});assert.equal(r.email,'');assert.equal(r.email_status,'identity_mismatch');});
 test('same-domain different person result is rejected',()=>{const r=setup().s.finderResult_({first_name:'Bob',last_name:'Example',domain:'example.com',email:'bob@example.com'},contact);assert.equal(r.email_status,'identity_mismatch');});
 test('high score cannot override catch-all result',()=>{const s=setup().s,r=s.verificationResult_({email:contact.email,status:'valid',score:100,accept_all:true},contact.email);assert.equal(r.email_status,'accept_all');assert.equal(s.contactCanPublish_({...contact,...r}),false);});
 for(const status of ['unknown','invalid','accept_all','disposable','webmail','blocked'])test(status+' is never published as verified',()=>{const s=setup().s,r=s.verificationResult_({email:contact.email,status},contact.email);assert.equal(s.contactCanPublish_({...contact,...r}),false);});
 test('valid mailbox alone cannot establish current employment or buying intent',()=>{assert.equal(setup().s.contactCanPublish_({...contact,identity_status:'unconfirmed'}),false);});
 test('expired and future verification dates cannot publish',()=>{const s=setup().s;assert.equal(s.contactCanPublish_({...contact,verified_on:'2001-01-01'}),false);assert.equal(s.contactCanPublish_({...contact,verified_on:'2999-01-01'}),false);});
 test('suppression persists and stops all requests',()=>{const e=setup();e.s.hunterRequest_=()=>{throw Error('must not request');};const suppressed=e.s.finderResult_({suppressed:true},contact);assert.equal(suppressed.do_not_contact,'yes');assert.equal(e.s.enrichContact_(suppressed).email_status,'suppressed');assert.equal(e.s.contactCanPublish_(suppressed),false);});
 test('fresh verified result is reused without spending',()=>{const e=setup();e.s.hunterRequest_=()=>{throw Error('unexpected paid call');};assert.equal(e.s.enrichContact_(contact).email,contact.email);});
 test('credit cap preserves zero and counts requests before results',()=>{const e=setup();e.s.reserveContactCredits_(1,e.store,'2026-09');assert.equal(JSON.parse(e.props.LH_CONTACT_CREDIT_BUDGET).reserved,1);assert.throws(()=>e.s.reserveContactCredits_(5,e.store,'2026-09'),/limit/);const z=setup({prospecting:{...pc,contacts:{...pc.contacts,monthly_credits:0}}});assert.throws(()=>z.s.reserveContactCredits_(.5,z.store,'2026-09'),/limit/);});
 test('contact cap resumes in a new month without deleting data',()=>{const e=setup();e.s.reserveContactCredits_(5,e.store,'2026-09');e.s.reserveContactCredits_(1,e.store,'2026-10');assert.deepEqual(JSON.parse(e.props.LH_CONTACT_CREDIT_BUDGET),{month:'2026-10',reserved:1});});
 test('corrupt credit ledger fails closed',()=>{const e=setup();e.props.LH_CONTACT_CREDIT_BUDGET='broken';assert.throws(()=>e.s.reserveContactCredits_(1,e.store,'2026-09'),/unreadable/);});
 test('failed durable budget save prevents provider request',()=>{const e=setup();e.props.HUNTER_KEY='fixture';let calls=0;e.store.setProperty=()=>{throw Error('write failed');};e.s.UrlFetchApp.fetch=()=>{calls++;};assert.throws(()=>e.s.hunterRequest_('email-finder',{domain:'example.com',full_name:'Alice Example'},1),/write failed/);assert.equal(calls,0);});
 test('HTTP failure keeps reservation and blocks immediate duplicate retry',()=>{const e=setup();e.props.HUNTER_KEY='fixture';let calls=0;e.s.UrlFetchApp.fetch=()=>{calls++;return{getResponseCode:()=>429};};assert.throws(()=>e.s.hunterRequest_('email-finder',{domain:'example.com',full_name:'Alice Example'},1),/HTTP 429/);assert.throws(()=>e.s.hunterRequest_('email-finder',{domain:'example.com',full_name:'Alice Example'},1),/already running/);assert.equal(calls,1);assert.equal(JSON.parse(e.props.LH_CONTACT_CREDIT_BUDGET).reserved,1);});
 test('Hunter key goes only in header and errors redact it',()=>{const e=setup();e.props.HUNTER_KEY='fixture-key';e.s.UrlFetchApp.fetch=(url,options)=>{assert.doesNotMatch(url,/fixture-key/);assert.equal(options.headers['X-API-KEY'],'fixture-key');return{getResponseCode:()=>200,getContentText:()=>'{"data":{"email":null}}'};};e.s.hunterRequest_('email-finder',{domain:'example.com',full_name:'Alice Example'},1);assert.equal(e.s.redactSecretText_('fixture-key'),'[redacted]');});
 test('manual mode cannot use Hunter even with key and credits',()=>{const e=setup({mode:'manual'});e.props.HUNTER_KEY='fixture';assert.throws(()=>e.s.hunterRequest_('email-finder',{},1),/disabled/);assert.equal(e.props.LH_CONTACT_CREDIT_BUDGET,undefined);});
 test('cold selected contact request does not scrape and promote website emails',()=>{const e=setup(),r={source:'cold_prospect',contact:'',people:'',lookup:''};e.s.lookupRow_(r,Date.now()+10000,{},{});assert.equal(r.contact,'');assert.match(r.lookup,/Find work contacts/);});
 test('changed mailbox cannot reuse an earlier valid result',()=>{const e=setup();assert.equal(e.s.contactCanPublish_({...contact,email:'bob@example.com'}),false);});
 test('verification refuses consumer address before calling provider',()=>{const e=setup();e.s.hunterRequest_=()=>{throw Error('should not call');};assert.throws(()=>e.s.enrichContact_({...contact,email:'alice@gmail.com'}),/business domain/);});
 test('HTTP 451 is durable independent of editable candidate rows',()=>{const e=setup();e.props.HUNTER_KEY='fixture';e.s.UrlFetchApp.fetch=()=>({getResponseCode:()=>451});assert.equal(e.s.hunterRequest_('domain-search',{domain:'example.com',limit:5},1).suppressed,true);assert.equal(e.s.contactSuppressed_({...contact,lead_id:'other-branch'}),true);assert.equal(e.s.contactCanPublish_(contact),false);});
 test('person suppression applies across duplicate leads',()=>{const e=setup();assert.equal(e.s.contactSuppressed_({...contact,lead_id:'other'},[{...contact,do_not_contact:'yes'}]),true);});
 test('contact publishing rechecks a suppression changed during lead lookup',()=>{const e=env([{id:contact.lead_id,website:'https://example.com',status:'new',contact:''}],{mode:'assisted',prospecting:pc});const rec={...contact};attachContacts(e,[rec]);e.s.confirmRow_=()=>{rec.do_not_contact='yes';return true;};e.s.publishVerifiedContacts();assert.equal(e.get(contact.lead_id,'email'),'');});
 test('contact publishing never overwrites sent rows or existing human contact',()=>{for(const extra of [{status:'sent',email:''},{status:'new',email:'Human value'}]){const e=env([{id:contact.lead_id,website:'https://example.com',...extra}],{mode:'assisted',prospecting:pc});attachContacts(e,[{...contact}]);e.s.publishVerifiedContacts();assert.equal(e.get(contact.lead_id,'email'),extra.email);}});
 test('cold rescore preserves a fresh verified available email route',()=>{const e=setup();attachContacts(e,[{...contact}]);const r=e.s.jevDerive_(answers(e),{id:contact.lead_id,source:'cold_prospect',website:'https://example.com',email:contact.email});assert.equal(r.channel,'Email');assert.equal(r.readiness_pct,'Unknown');});
 test('contact write follows stable ID after a sort and changes only enrichment fields',()=>{const e=setup(),a={...contact},b={...contact,contact_id:'c2',name:'Bob Example',note:'Research formula result'},f=attachContacts(e,[a,b]);const before=e.s.contactRows_(f.sheet)[0];f.records.reverse();assert.equal(e.s.commitContact_(f.sheet,before,{...before,email_status:'unknown',note:'Updated'}),true);assert.equal(a.email_status,'unknown');assert.equal(b.note,'Research formula result');assert.ok(f.writes.every(w=>w.row===3&&[10,14].includes(w.col)));});
 test('contact write preserves edits made while provider is running',()=>{const e=setup(),r={...contact},f=attachContacts(e,[r]);const before=e.s.contactRows_(f.sheet)[0];r.role='New human role';assert.equal(e.s.commitContact_(f.sheet,before,{...before,email_status:'invalid'}),false);assert.equal(f.writes.length,0);});
 test('contact IDs must be unique before processing',()=>{const e=setup(),f=attachContacts(e,[{...contact},{...contact}]);assert.throws(()=>e.s.contactRows_(f.sheet),/duplicated/);});
 test('cold scoring context excludes hypotheses even when notes retain them',()=>{const s=setup().s;const text=s.coldEvidenceText_({company:'Example',notes:'Observed facts: two clinics\nHypothesis (unconfirmed): definitely needs our system'});assert.match(text,/two clinics/);assert.doesNotMatch(text,/definitely|Hypothesis/);});
 test('stale discovery snapshot does not cache discarded results',()=>{const e=discoveryFixture([coldLead]);let calls=0;e.s.hunterRequest_=()=>{if(++calls===1)e.set(coldLead.id,'notes','Owner edit during lookup');return domainResult;};e.s.findWorkContactsSelected();assert.equal(e.records.length,0);e.s.findWorkContactsSelected();assert.equal(calls,2);assert.equal(e.records.length,1);});
 test('pending discovery remains eligible for later retry',()=>{const e=discoveryFixture([coldLead]);let calls=0;e.s.hunterRequest_=()=>++calls===1?{pending:true}:domainResult;e.s.findWorkContactsSelected();e.s.findWorkContactsSelected();assert.equal(calls,2);assert.ok(e.records.some(c=>c.name===contact.name));});
 test('branch cache reuses research without inheriting publication ownership',()=>{const branch={...coldLead,id:'cold:branch',email:contact.email},e=discoveryFixture([coldLead,branch]);let calls=0;e.s.hunterRequest_=()=>{calls++;return domainResult;};e.s.findWorkContactsSelected();e.records[0].published_email=contact.email;e.select(4);e.s.findWorkContactsSelected();assert.equal(calls,1);const copied=e.records.find(c=>c.lead_id===branch.id);assert.equal(copied.identity_status,'unconfirmed');assert.equal(copied.published_email,'');assert.equal(e.get(branch.id,'email'),contact.email);});
 test('suppression revokes only an email previously copied by this script',()=>{const e=env([{...coldLead,email:contact.email,channel:'Email'}],{mode:'assisted',prospecting:pc});const rec={...contact,published_email:contact.email,do_not_contact:'yes'};attachContacts(e,[rec]);e.s.reconcilePublishedContacts_();assert.equal(e.get(coldLead.id,'email'),'');assert.equal(e.get(coldLead.id,'channel'),'Find contact first');assert.equal(rec.published_email,'');});
 test('revocation preserves owner replacement and sent history',()=>{for(const extra of [{email:'Owner replacement',status:'new'},{email:contact.email,status:'sent'}]){const e=env([{...coldLead,...extra}],{mode:'assisted',prospecting:pc});attachContacts(e,[{...contact,published_email:contact.email,do_not_contact:'yes'}]);e.s.reconcilePublishedContacts_();assert.equal(e.get(coldLead.id,'email'),extra.email);}});
 test('suppression during finder prevents subsequent verifier request',()=>{const e=setup(),rec={...contact,email:'',verified_email:'',email_status:'unverified'},f=attachContacts(e,[rec]);let calls=0;e.s.hunterRequest_=endpoint=>{calls++;assert.equal(endpoint,'email-finder');f.records[0].do_not_contact='yes';return{first_name:'Alice',last_name:'Example',domain:'example.com',email:contact.email};};const result=e.s.enrichContact_(rec);assert.equal(calls,1);assert.equal(result.do_not_contact,'yes');});
 test('domain suppression is reflected on every contact row for priority',()=>{const e=setup(),rec={...contact};attachContacts(e,[rec]);e.store.setProperty(e.s.contactSuppressionKey_('domain:example.com'),'yes');e.s.reconcilePublishedContacts_();assert.equal(rec.do_not_contact,'yes');});

}
