import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import crypto from 'node:crypto';import {pathToFileURL} from 'node:url';import path from 'node:path';
const dir=process.argv[2]||new URL('../',import.meta.url);const read=n=>fs.readFileSync(new URL(n,typeof dir==='string'?pathToFileURL(path.resolve(dir)+'/'):dir),'utf8');
const s={console,Utilities:{DigestAlgorithm:{SHA_256:1},Charset:{UTF_8:1},computeDigest:(_,v)=>Array.from(crypto.createHash('sha256').update(v).digest())}};vm.createContext(s);
vm.runInContext(['Code.gs','Hunter.gs','Apollo.gs','ContactGuidance.gs'].filter(n=>fs.existsSync(new URL(n,typeof dir==='string'?pathToFileURL(path.resolve(dir)+'/'):dir))).map(read).join('\n')+'\nthis.T={LEAD_COLS,CONTACT_COLS,leadFieldValue_,publicPhonesFromHtml_,contactGuidance_,cellFillHash_,cellFillPlan_,cellEstimate_};',s);
const T=s.T;let n=0;const test=(name,f)=>{f();n++;console.log('PASS '+name);};
test('Contact, email and phone are separate visible fields',()=>assert.deepEqual(Array.from(T.LEAD_COLS).slice(12,16),['contact','email','phone','people']));
test('Display guidance is missing data and never contact evidence',()=>{assert.equal(T.leadFieldValue_('email','[Next] Hunter email · up to 1.5 credits/person'),'');assert.equal(T.leadFieldValue_('contact','@owner'),'@owner');assert.equal(T.leadFieldValue_('notes','[Next] user note'),'[Next] user note');});
test('Guidance changes do not invalidate queues; real edits do',()=>{const a={id:'a',email:''},b={...a,email:'[Next] Public website · 0 credits'};assert.equal(T.cellFillHash_(a),T.cellFillHash_(b));assert.notEqual(T.cellFillHash_(a),T.cellFillHash_({...a,email:'owner@example.com'}));});
test('Phone extraction accepts explicit public contact markup, not prices/dates',()=>{const p=T.publicPhonesFromHtml_('<a href="tel:+1-415-555-0123">Call</a><script type="application/ld+json">{"telephone":"+1 (415) 555-0123"}</script> Price 99999999 Date 2026-09-28');assert.equal(p.length,1);assert.equal(p[0],'+14155550123');assert.equal(T.publicPhonesFromHtml_('order 1234567890, price $12345678').length,0);});
test('Invalid and premium/unsafe href values are rejected',()=>{assert.equal(T.publicPhonesFromHtml_('<a href="tel:123">x</a><a href="tel:javascript:1234567890">x</a>').length,0);});
test('Phone-only selection is free; missing website is an explicit dependency',()=>{const p=T.cellFillPlan_({company:'Example',website:'https://example.com'},['phone']);assert.equal(T.cellEstimate_(p.fields),0);assert.deepEqual(Array.from(p.fields),['phone']);assert.ok(T.cellFillPlan_({company:'Example'},['phone']).fields.includes('website'));});
test('No phone attempt recommends free pages first',()=>assert.match(T.contactGuidance_({company:'Example',website:'https://example.com'},'phone',[]),/Public contact pages.*0 credits/));
test('No public number recommends capped person-phone lookup',()=>assert.match(T.contactGuidance_({company:'Example',website:'https://example.com',_phoneChecked:true},'phone',[]),/Apollo.*9 credits/));
test('Suppressed contacts never recommend another provider',()=>assert.match(T.contactGuidance_({domain:'example.com',provider_person_id:'p',do_not_contact:'yes'},'email',[]),/Do not contact/));
test('Email fallback has prerequisites and correct ceiling',()=>{assert.match(T.contactGuidance_({company:'Example',website:'https://example.com'},'email',[]),/Apollo.*0 credits/);assert.match(T.contactGuidance_({domain:'example.com',name:'Alice Example',identity_status:'confirmed'},'email',[]),/Hunter.*1.5 credits/);assert.match(T.contactGuidance_({company:'Example'},'email',[]),/Confirm website/);});
console.log(`${n} contact guidance checks passed`);
// Integration fixtures exercise actual reads/writes and never use a real account.
const H=Array.from(T.LEAD_COLS),C=Array.from(T.CONTACT_COLS);let requests=0;
const props={};s.PropertiesService={getScriptProperties:()=>({getProperty:k=>props[k]??null})};
function sheet(name,records,header,offset){
  const grid=[...Array.from({length:offset},()=>[]),header,...records.map(r=>header.map(k=>r[k]??'')),...Array.from({length:6},()=>[])],notes=new Map();
  return {grid,notes,getName:()=>name,getDataRange:()=>({getValues:()=>grid.map(r=>header.map((_,k)=>r[k]??''))}),getLastRow:()=>grid.length,getRange(r,c,rows=1,cols=1){return {
    getValues:()=>Array.from({length:rows},(_,n)=>Array.from({length:cols},(_,k)=>grid[r-1+n]?.[c-1+k]??'')),getValue:()=>grid[r-1]?.[c-1]??'',
    setValues(v){v.forEach((row,n)=>row.forEach((value,k)=>{grid[r-1+n][c-1+k]=value;}));},setValue(v){grid[r-1][c-1]=v;},
    getNotes:()=>Array.from({length:rows},(_,n)=>[notes.get(r+n)||'']),setNote:v=>notes.set(r,v)};
  }};
}
let leadSheet,contactSheet;const reset=(leads,contacts=[])=>{leadSheet=sheet('Leads',leads,H,1);contactSheet=sheet('Contacts',contacts,C,0);s.SpreadsheetApp={getActive:()=>({getSheetByName:n=>n==='Leads'?leadSheet:n==='Contacts'?contactSheet:null})};};
const get=(id,k)=>leadSheet.grid.find(r=>r[H.indexOf('id')]===id)?.[H.indexOf(k)];
const lead={id:'a',company:'Example',website:'https://example.com',contact:'@owner',status:'new',next_step:'Skip',match_pct:5};
test('Backfill preserves handles and real data and leaves unused rows empty',()=>{reset([{...lead,contact:'@owner · hello@example.com'},{...lead,id:'b',email:'human@example.com',phone:'Public: +441234567890'}]);s.refreshContactGuidance_();assert.equal(get('a','contact'),'@owner · hello@example.com');assert.equal(get('a','email'),'hello@example.com');assert.equal(get('b','email'),'human@example.com');assert.equal(get('b','phone'),'Public: +441234567890');assert.ok(leadSheet.grid.slice(4).every(r=>r.every(v=>v==='')));assert.equal(s.refreshContactGuidance_(),0);});
test('Contact labels stay empty to verification and do not create fake records',()=>{reset([lead],[{lead_id:'a',contact_id:'p',domain:'example.com',name:'Alice Example',identity_status:'confirmed',provider_person_id:'p'}]);s.refreshContactGuidance_();const c=s.contactRows_(contactSheet)[0];assert.equal(c.email,'');assert.equal(c.phone,'');assert.equal(c.linkedin,'');assert.equal(s.contactCanPublish_(c),false);});
test('Backfill does not recommend bypassing persistent suppression',()=>{reset([lead],[{lead_id:'a',contact_id:'p',domain:'example.com',name:'Alice Example',identity_status:'confirmed'}]);props[s.contactSuppressionKey_('domain:example.com')]='yes';s.refreshContactGuidance_();assert.match(contactSheet.grid[1][C.indexOf('email')],/Do not contact/);delete props[s.contactSuppressionKey_('domain:example.com')];});
test('Guidance follows stable IDs after sorting and preserves a human replacement',()=>{reset([lead,{...lead,id:'b'}]);const at=H.indexOf('email');leadSheet.grid[2][at]='Human replacement';[leadSheet.grid[2],leadSheet.grid[3]]=[leadSheet.grid[3],leadSheet.grid[2]];s.guidanceWrites_(leadSheet,at+1,[{id:'a',row:3,expected:'',value:'[Next] first'},{id:'b',row:4,expected:'',value:'[Next] second'}]);assert.equal(get('a','email'),'Human replacement');assert.equal(get('b','email'),'[Next] second');});
test('Explicit free phone lookup processes skipped leads and follows a sort',()=>{reset([lead,{...lead,id:'b',phone:'Human number'}]);s.findContactsFree_=()=>{requests++;[leadSheet.grid[2],leadSheet.grid[3]]=[leadSheet.grid[3],leadSheet.grid[2]];return {phones:[{number:'+14155550123',source_url:'https://example.com/contact'}],readable:1};};const result=s.findPublicPhonesForIds_(['a'],Date.now()+60000);assert.equal(result.found,1);assert.equal(get('a','phone'),'Public: +14155550123');assert.equal(get('b','phone'),'Human number');assert.equal(get('a','next_step'),'Skip');assert.match(leadSheet.notes.get(4),/person ownership unconfirmed.*example.com\/contact/);});
test('Human edit during free phone research prevents stale writes',()=>{reset([lead]);s.findContactsFree_=()=>{leadSheet.grid[2][H.indexOf('phone')]='Human number';return {phones:[{number:'+14155550123',source_url:'https://example.com/contact'}],readable:1};};assert.equal(s.findPublicPhonesForIds_(['a'],Date.now()+60000).checked,0);assert.equal(get('a','phone'),'Human number');});
test('Unreadable pages remain uncertain; an empty readable result shows requested fallback',()=>{reset([lead]);s.findContactsFree_=()=>({phones:[],readable:0});s.findPublicPhonesForIds_(['a'],Date.now()+60000);s.refreshContactGuidance_();assert.match(leadSheet.notes.get(3),/Pages unreadable; no conclusion/);assert.match(get('a','phone'),/Apollo.*9 credits/);assert.equal(s.leadData_(leadSheet)[1][H.indexOf('phone')],'');});
test('Structured organization phone is accepted; testimonial person is not assigned',()=>{assert.equal(T.publicPhonesFromHtml_('<script type="application/ld+json">{"@type":"Organization","telephone":"020 7946 0123"}</script>')[0],'02079460123');assert.equal(T.publicPhonesFromHtml_('<script type="application/ld+json">{"@type":"Person","telephone":"020 7946 0123"}</script>').length,0);});
test('Visible labeled phone is supported without mistaking dates or script text for contacts',()=>{assert.equal(T.publicPhonesFromHtml_('<p>Call us at (415) 555-0123</p>')[0],'4155550123');assert.equal(T.publicPhonesFromHtml_('Call 2026-09-28').length,0);assert.equal(T.publicPhonesFromHtml_('<script>Phone: +1-415-555-0123</script> order 123456789').length,0);});
console.log(`${n} total contact checks passed; no external requests.`);
